[pytest]
testpaths = .
python_files = test_*.py
collect_ignore_glob = 
    **/wwwroot/**
    **/node_modules/**
    **/site-packages/**
    **/__pycache__/**
    **/Currere-backend/**
    **/currere-frontend/**
    **/Currere.Tests/**
    **/Currere-extension/**
    **/currere-cli/**
